import test from 'node:test';import assert from 'node:assert/strict';import {createFetcher,parseRobots,robotsAllows} from '../scripts/http.mjs';
const response=(text='',status=200,headers={})=>new Response(text,{status,headers:{'content-type':'text/plain',...headers}});
function setup(handler,options={}){let time=0;const calls=[];const get=createFetcher({allowedHosts:['official.test'],clock:()=>time,pause:async ms=>{time+=ms;},fetchImpl:async(url,init)=>{calls.push({url,time,init});return url.endsWith('/robots.txt')?response('User-agent: *\nDisallow: /private\nCrawl-delay: 10'):handler(url,init);},...options});return {get,calls};}
test('Robots wildcard, specificity and delay rules',()=>{const p=parseRobots('User-agent: *\nDisallow: /search/\nAllow: /search/public$\nCrawl-delay: 10');assert.equal(p.delay,10000);assert.equal(robotsAllows(p,'https://official.test/search/private'),false);assert.equal(robotsAllows(p,'https://official.test/search/public'),true);assert.equal(robotsAllows(p,'https://official.test/search/public/other'),false);});
test('Agent-specific robots overrides wildcard groups',()=>{const p=parseRobots('User-agent: *\nDisallow: /\nUser-agent: JazzWatch\nAllow: /');assert.equal(robotsAllows(p,'https://official.test/'),true);});
test('Every request including robots is counted; shared cache and crawl delay',async()=>{const {get,calls}=setup(()=>response('ok'));await get('https://official.test/a');await get('https://official.test/a');await get('https://official.test/b');assert.equal(calls.length,3);assert.ok(calls[1].time-calls[0].time>=10000);assert.ok(calls[2].time-calls[1].time>=10000);assert.equal(get.stats().requests,3);});
test('Robots disallow prevents document request',async()=>{const {get,calls}=setup(()=>response('ok'));await assert.rejects(get('https://official.test/private/x'),/disallows/);assert.equal(calls.length,1);});
for(const status of [401,403,404,429])test('HTTP '+status+' is not retried',async()=>{const {get,calls}=setup(()=>response('denied',status));await assert.rejects(get('https://official.test/a'),new RegExp('HTTP '+status));assert.equal(calls.length,2);});
test('Transient status retries once, counted and paced',async()=>{let n=0;const {get,calls}=setup(()=>++n===1?response('',503):response('ok'));assert.equal(await get('https://official.test/a'),'ok');assert.equal(calls.length,3);assert.ok(calls[2].time-calls[1].time>=10000);});
test('Redirect cannot escape allowlist',async()=>{const {get,calls}=setup(()=>response('',302,{location:'https://other.test/'}));await assert.rejects(get('https://official.test/a'),/allowlist/);assert.equal(calls.length,2);});
test('Redirect to disallowed path blocked',async()=>{const {get,calls}=setup(()=>response('',302,{location:'/private'}));await assert.rejects(get('https://official.test/a'),/disallows/);assert.equal(calls.length,2);});
test('Redirect loops terminate at finite request count',async()=>{const {get,calls}=setup(()=>response('',302,{location:'/loop'}));await assert.rejects(get('https://official.test/a'),/Redirect limit/);assert.equal(calls.length,5);});
test('Streaming body size cap is enforced',async()=>{const {get}=setup(()=>response('x'.repeat(300)),{maxBytes:100});await assert.rejects(get('https://official.test/a'),/byte budget/);});
test('Unexpected binary content rejected',async()=>{const {get}=setup(()=>response('image',200,{'content-type':'image/png'}));await assert.rejects(get('https://official.test/a'),/content type/);});
test('Request ceiling includes robots and retries',async()=>{const {get,calls}=setup(()=>response('',503),{requestLimit:2});await assert.rejects(get('https://official.test/a'),/budget/);assert.equal(calls.length,2);});
test('YouTube is never collected even if accidentally allowlisted',()=>{const {get}=setup(()=>response('ok'),{allowedHosts:['www.youtube.com']});assert.throws(()=>get('https://www.youtube.com/watch?v=x'),/allowlist/);});

